SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `CONFIG` (
  `ID` int(3) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `FIELD` varchar(255) NOT NULL COMMENT '键名',
  `VALUE` longtext NOT NULL,
  `ENABLE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`FIELD`)
) ENGINE=InnoDB  DEFAULT CHARSET=UTF8 COMMENT='网站配置' AUTO_INCREMENT=1 ;

CREATE TABLE `TEMPLATE` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `guid` varchar(36) NOT NULL,
  `name` varchar(512) DEFAULT NULL,
  `content` text COMMENT '内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
