CREATE TABLE `TB_USERS` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_NAME` varchar(32) DEFAULT NULL COMMENT '登录账户',
  `PASSWORD` varchar(512) DEFAULT NULL COMMENT '密码',
  `STATUS` varchar(32) DEFAULT NULL COMMENT '账户状态',
  `TAGS` text COMMENT '标签列表',
  `GMT_CREATED` datetime DEFAULT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;